---
title: "Figure 12"
author: '##### Manon Makino'
date: '2023-02-21'
output: html_document
---

# Plotting the figures 12 and Appendix 8

Plotting the figures a,b combined

## Loading scripts

```{r}
source("../../param.R")
source("../../package.R")
```

## Setting parameters

### fixed setting

```{r}
PDEG <- param$pdeg
data.name <- param$simdata.name
name <- data.name[1]
N_trial <- 50
```

### manual setting

```{r}
n1 <- 3
```

## Formatting data

### preparation

```{r}
colname.list <- NULL
for (pdeg in PDEG){
  colname <- paste("PDEG = ", pdeg, sep = "")
  colname.list <- c(colname.list, colname)
}
rowname.list <- 1:N_trial

MBCdeg2_1 <- MBCdeg3_1 <- MBCdeg4_1 <- MBCdeg5_1 <- MBCdeg2_2 <- MBCdeg3_2 <- MBCdeg4_2 <- MBCdeg5_2 <- MBCdeg2_3 <- MBCdeg3_3 <- MBCdeg4_3 <- MBCdeg5_3 <- matrix(0, ncol = length(PDEG), nrow = N_trial)
colnames(MBCdeg2_1) <- colnames(MBCdeg3_1) <- colnames(MBCdeg4_1) <- colnames(MBCdeg5_1) <- colnames(MBCdeg2_2) <- colnames(MBCdeg3_2) <- colnames(MBCdeg4_2) <- colnames(MBCdeg5_2) <- colnames(MBCdeg2_3) <- colnames(MBCdeg3_3) <- colnames(MBCdeg4_3) <- colnames(MBCdeg5_3) <- colname.list
rownames(MBCdeg2_1) <- rownames(MBCdeg3_1) <- rownames(MBCdeg4_1) <- rownames(MBCdeg5_1) <- rownames(MBCdeg2_2) <- rownames(MBCdeg3_2) <- rownames(MBCdeg4_2) <- rownames(MBCdeg5_2) <- rownames(MBCdeg2_3) <- rownames(MBCdeg3_3) <- rownames(MBCdeg4_3) <- rownames(MBCdeg5_3) <- rowname.list

label1 <- paste("(PG1, PG2, PG3)\n", "(1/3, 1/3, 1/3)", sep = "")
label2 <- paste("(PG1, PG2, PG3)\n", "(0.6, 0.2, 0.2)", sep = "")
label3 <- paste("(PG1, PG2, PG3)\n", "(0.5, 0.5, 0)", sep = "")
label4 <- paste("(PG1, PG2, PG3)\n", "(1.0, 0, 0)", sep = "")

matome <- NULL
```

### Creating original data

```{r}
for (assign in param$assign$`3group`){
  P1 <- assign[1]
  
  for(i in 1:ncol(MBCdeg1_2)){
    in_f <- paste("../auc_3group_", name, "_", PDEG, "_", round(P1, digits = 2), "_fixed_n", n1, ".txt", sep = "")
    data <- read.table(in_f,header = TRUE, sep = "\t")
    edgeR[,i] <- data$edgeR
    DESeq2[,i] <- data$DESeq2
    TCC[,i] <- data$TCC
    MBCdeg1_2[,i] <- data$MBCdeg1_K2
    MBCdeg1_3[,i] <- data$MBCdeg1_K3
    MBCdeg1_4[,i] <- data$MBCdeg1_K4
    MBCdeg1_5[,i] <- data$MBCdeg1_K5
    MBCdeg2_2[,i] <- data$MBCdeg2_K2
    MBCdeg2_3[,i] <- data$MBCdeg2_K3
    MBCdeg2_4[,i] <- data$MBCdeg2_K4
    MBCdeg2_5[,i] <- data$MBCdeg2_K5
    MBCdeg3_2[,i] <- data$MBCdeg3_K2
    MBCdeg3_3[,i] <- data$MBCdeg3_K3
    MBCdeg3_4[,i] <- data$MBCdeg3_K4
    MBCdeg3_5[,i] <- data$MBCdeg3_K5
  }
  if (P1 == 0.33){
    P <- "lab1"
  }else if (P1 == 0.6){
    P <- "lab2"
  }else if (P1 == 0.5){
    P <- "lab3"
  }else if (P1 == 1){
    P <- "lab4"
  }
  
  datedgeR <- data.frame(Method = "a", P1 = P, melt(edgeR))
  datDESeq2 <- data.frame(Method = "b", P1 = P, melt(DESeq2))
  datTCC <- data.frame(Method = "c", P1 = P, melt(TCC))
  datMBCdeg1_2 <- data.frame(Method = "d1", P1 = P, melt(MBCdeg1_2))
  datMBCdeg1_3 <- data.frame(Method = "d1", P1 = P, melt(MBCdeg1_3))
  datMBCdeg1_4 <- data.frame(Method = "d1", P1 = P, melt(MBCdeg1_4))
  datMBCdeg1_5 <- data.frame(Method = "d1", P1 = P, melt(MBCdeg1_5))
  datMBCdeg2_2 <- data.frame(Method = "d2", P1 = P, melt(MBCdeg2_2))
  datMBCdeg2_3 <- data.frame(Method = "d2", P1 = P, melt(MBCdeg2_3))
  datMBCdeg2_4 <- data.frame(Method = "d2", P1 = P, melt(MBCdeg2_4))
  datMBCdeg2_5 <- data.frame(Method = "d2", P1 = P, melt(MBCdeg2_5))
  datMBCdeg3_2 <- data.frame(Method = "d3", P1 = P, melt(MBCdeg3_2))
  datMBCdeg3_3 <- data.frame(Method = "d3", P1 = P, melt(MBCdeg3_3))
  datMBCdeg3_4 <- data.frame(Method = "d3", P1 = P, melt(MBCdeg3_4))
  datMBCdeg3_5 <- data.frame(Method = "d3", P1 = P, melt(MBCdeg3_5))
  
  dat <- rbind(datedgeR, datDESeq2, datTCC, datMBCdeg1_2, datMBCdeg1_3, datMBCdeg1_4, datMBCdeg1_5, datMBCdeg2_2, datMBCdeg2_3, datMBCdeg2_4, datMBCdeg2_5, datMBCdeg3_2, datMBCdeg3_3, datMBCdeg3_4, datMBCdeg3_5)
  matome <- rbind(matome, dat)
}

colnames(matome) <- c("Method", "Assign", "rep", "PDEG", "AUC")
labs <- c(label1, label2, label3, label4)
names(labs) <- c("lab1", "lab2", "lab3", "lab4")
```

## Plotting

```{r}
g <- ggplot(matome, aes(x = Method, y = AUC, fill = Method))
g <- g + theme_bw()
g <- g + labs(x = "", y = "AUC" , color = "Method")
g <- g + scale_x_discrete(label=c("", "K = 2", "", "", "K = 3", "", "", "K = 4", "", "", "K = 5", ""))
g <- g + scale_color_manual(values = c("#8a2be2", "#cd853f", "#696969", rep(c("#FF367F", "#4689FF", "#009900"), 4))) + scale_fill_manual(values = rep("white", 15))
g <- g + scale_y_continuous(limit = c(0, 1.0))
g <- g + geom_boxplot(aes(col = Method))
g <- g + theme(axis.title.y = element_text(size = 18, face = "bold"), 
               axis.text.x = element_text(size = 13, face = "bold", angle = 90), 
               axis.text.y = element_text(size = 13, face = "bold"), 
               strip.text.x = element_text(size = 16, face = "bold.italic"), 
               strip.text.y = element_text(size = 16, face = "bold.italic"), 
               legend.box = "horizontal",  
               legend.position = "none", 
               legend.title = element_text(size = 15, face = "bold"), 
               legend.text = element_text(size = 13), 
               panel.grid.major.x = element_blank())
g <- g + facet_grid(PDEG ~ Assign, labeller = labeller(Assign = labs))

plot(g)
```


## Output

```{r}
out_f <- paste("test_tcc_fixed_multi_n", n1, ".png", sep = "")
ggsave(file = out_f, plot = g, dpi = 300, width= 10, height = 15)
```


